stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - frtr
  before_script:
    - export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
    - which docker || echo "Docker not in PATH, trying direct path"
  script:
    # Создаем .env файл
    - |
      cat > .env << EOF
      BOT_TOKEN=$BOT_TOKEN
      ADMIN_TG_ID=$ADMIN_TG_ID
      CRYPTO_BOT_TOKEN=$CRYPTO_BOT_TOKEN
      YOOMONEY_TOKEN=$YOOMONEY_TOKEN
      YOOMONEY_WALLET=$YOOMONEY_WALLET
      YOOMONEY_NOTIFICATION_SECRET=$YOOMONEY_NOTIFICATION_SECRET
      ADMIN_USERNAME=$ADMIN_USERNAME
      ADMIN_PASSWORD=$ADMIN_PASSWORD
      SECRET_SESSION_KEY=$SECRET_SESSION_KEY
      R2_ACCESS_KEY=$R2_ACCESS_KEY
      R2_SECRET_KEY=$R2_SECRET_KEY
      R2_ENDPOINT=$R2_ENDPOINT
      R2_PUBLIC_URL=$R2_PUBLIC_URL
      DEBUG=false
      EOF


    # Даем права на скрипты
    - chmod +x scripts/entrypoint.sh

    # Останавливаем старые контейнеры
    - docker compose down || true

    # Запускаем новые контейнеры
    - docker compose up -d --build --force-recreate --no-cache
  only:
    - main
  when: manual
  environment:
    name: production