
version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"        # внешне 8000 → внутрь контейнера 8000
    depends_on:
      - redis
      - minio
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_HOST: minio
      MINIO_PORT: "9000"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data   # чтобы данные сохранялись между перезапусками


  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    container_name: minio_test
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
      - ./init.sh:/usr/bin/init.sh:ro
    entrypoint: ["/usr/bin/init.sh"]

volumes:
  redis-data:
  minio-data:

