"""Remove column

Revision ID: d6db57430dc3
Revises: 212a16087930
Create Date: 2025-08-01 16:22:03.691686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d6db57430dc3"
down_revision: Union[str, None] = "212a16087930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "subtitle")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("subtitle", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
