"""Changed porducts db

Revision ID: 99352bfed34d
Revises: cee264c6b850
Create Date: 2025-07-17 17:17:58.409193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99352bfed34d'
down_revision: Union[str, None] = 'cee264c6b850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=False))
    op.add_column('products', sa.Column('subtitle', sa.String(), nullable=False))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=False))
    op.drop_column('products', 'mimetype')
    op.drop_column('products', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('data', sa.BLOB(), nullable=False))
    op.add_column('products', sa.Column('mimetype', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('products', 'rating')
    op.drop_column('products', 'subtitle')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
