"""Add foreignkey and relationship with categories in users table

Revision ID: d7b2adae2e69
Revises: fed2a10f83da
Create Date: 2025-11-02 13:18:32.437224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d7b2adae2e69"
down_revision: Union[str, None] = "fed2a10f83da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_title", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_products_category_title", "categorys", ["category_title"], ["title"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint("fk_products_category_title", type_="foreignkey")
        batch_op.drop_column("category_title")

    # ### end Alembic commands ###
