"""Add table Categories

Revision ID: bced35cafb66
Revises: cd33514d2984
Create Date: 2025-11-02 11:15:28.983962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bced35cafb66'
down_revision: Union[str, None] = 'cd33514d2984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_table('categorys')
    # ### end Alembic commands ###
